Support configuration of custom systemctl status command
fractaledmind/litestream-ruby pull request #39
Opened 2024-09-04 11:42 UTC by rossta

I use systemd in production with litestream-ruby (on Hatchbox). When I check the status of Litestream in the litestream-ruby web ui, the status reported is "not running".

![Screenshot 2024-09-04 at 7 34 18 AM](https://github.com/user-attachments/assets/4c683ac0-609d-40c1-ae8d-d95248385c0d)

The reason this is happening is that built-in command for litestream-ruby to check the status of the litestream process returns an error message:

```
$ systemctl status litestream
Unit litestream.service could not be found.
```

On Hatchbox, I need to use a slightly different command to check the status:

```
$ systemctl --user status myapp-litestream.service
● myapp-litestream.service - myapp-litestream
     Loaded: loaded (/home/deploy/.config/systemd/user/myapp-litestream.service; enabled; vendor preset: enabled)
     Active: active (running) since Wed YYYY-MM-DD HH:MM:SS UTC; 20min ago
   Main PID: <PID> (ruby)
   # ...
```

To address this, the approach I had in mind is to make the systemctl status command configurable.

2024-09-06 15:09 UTC, fractaledmind requested changes
Some changes needed given the evolving direction of the library

2024-09-06 15:09 UTC, fractaledmind commented on lib/litestream.rb
> +    attr_accessor :systemctl_status_command
I am deprecating this way of setting new configuration. See recent releases for new preference

2024-09-06 15:09 UTC, fractaledmind commented on lib/litestream.rb
> +    attr_accessor :systemctl_status_command
Let's change the name to `systemctl_command`

2024-09-06 15:09 UTC, fractaledmind commented on lib/litestream.rb
> +        systemctl_status = `#{command}`.chomp
When you move this to an accessor on the module, I want the default to live in the getter so we can do:
```suggestion
        systemctl_status = `#{Litestream.systemctl_command}`.chomp
```

2024-09-07 00:36 UTC, rossta commented
Sounds good, updated the PR with the requested changes.

2024-09-16 14:28 UTC, rossta commented on lib/litestream.rb
> +        systemctl_status = `#{command}`.chomp
Done!

2024-09-16 14:28 UTC, rossta commented on lib/litestream.rb
> +    attr_accessor :systemctl_status_command
Done!

2024-10-22 17:24 UTC, fractaledmind approved these changes
LGTM

2024-10-22 17:24 UTC, merged

2024-10-22 17:31 UTC, fractaledmind commented
Released in v0.12.0